CITY_SUMMARY_QUERY = """
SELECT
    CITY,
    TOTAL_OBSERVATIONS,
    AVG_TEMPERATURE,
    MIN_TEMPERATURE,
    MAX_TEMPERATURE,
    AVG_HUMIDITY,
    MAX_WIND_SPEED,
    TOTAL_PRECIPITATION
FROM WEATHER_DB.ANALYTICS.CITY_WEATHER_SUMMARY
ORDER BY CITY
"""


DAILY_SUMMARY_QUERY = """
SELECT
    CITY,
    WEATHER_DATE,
    OBSERVATIONS,
    AVG_TEMPERATURE,
    MIN_TEMPERATURE,
    MAX_TEMPERATURE,
    AVG_HUMIDITY,
    MAX_WIND_SPEED,
    TOTAL_PRECIPITATION
FROM WEATHER_DB.ANALYTICS.DAILY_WEATHER_SUMMARY
ORDER BY WEATHER_DATE, CITY
"""


LATEST_WEATHER_QUERY = """
SELECT
    CITY,
    WEATHER_TIME,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WIND_SPEED,
    PRECIPITATION,
    WEATHER_CODE,
    TEMP_CATEGORY,
    WIND_CATEGORY
FROM WEATHER_DB.ANALYTICS.LATEST_WEATHER
ORDER BY CITY
"""


WEATHER_TREND_QUERY = """
SELECT
    CITY,
    WEATHER_TIME,
    TEMPERATURE,
    HUMIDITY,
    WIND_SPEED,
    PRECIPITATION
FROM WEATHER_DB.ANALYTICS.WEATHER_ANALYTICS_DT
ORDER BY WEATHER_TIME
"""