USE DATABASE WEATHER_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS WEATHER_RAW (
    CITY VARCHAR,
    WEATHER_TIME TIMESTAMP_NTZ,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    PRESSURE FLOAT,
    WIND_SPEED FLOAT,
    WEATHER_CODE INTEGER,
    PRECIPITATION FLOAT
);

CREATE STAGE IF NOT EXISTS WEATHER_STAGE;

CREATE FILE FORMAT IF NOT EXISTS WEATHER_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');