USE DATABASE WEATHER_DB;
USE SCHEMA STAGING;

CREATE TABLE IF NOT EXISTS WEATHER_STAGING (
    CITY VARCHAR,
    WEATHER_TIME TIMESTAMP_NTZ,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    PRESSURE FLOAT,
    WIND_SPEED FLOAT,
    WEATHER_CODE INTEGER,
    PRECIPITATION FLOAT
);