USE DATABASE WEATHER_DB;
USE SCHEMA STAGING;

CREATE TASK IF NOT EXISTS LOAD_WEATHER_STAGING
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'WEATHER_DB.RAW.WEATHER_RAW_STREAM'
    )
AS
INSERT INTO WEATHER_STAGING (
    CITY,
    WEATHER_TIME,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WIND_SPEED,
    WEATHER_CODE,
    PRECIPITATION
)
SELECT
    UPPER(TRIM(CITY)),
    WEATHER_TIME,
    ROUND(TEMPERATURE, 2),
    ROUND(HUMIDITY, 2),
    ROUND(PRESSURE, 2),
    ROUND(WIND_SPEED, 2),
    WEATHER_CODE,
    ROUND(PRECIPITATION, 2)
FROM WEATHER_DB.RAW.WEATHER_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

ALTER TASK WEATHER_DB.STAGING.LOAD_WEATHER_STAGING RESUME;