USE DATABASE WEATHER_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE TASK LOAD_WEATHER_STAGING
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('WEATHER_DB.RAW.WEATHER_RAW_STREAM')
AS
MERGE INTO WEATHER_STAGING AS target
USING (
    SELECT
        CITY,
        WEATHER_TIME,
        TEMPERATURE,
        HUMIDITY,
        PRESSURE,
        WIND_SPEED,
        WEATHER_CODE,
        PRECIPITATION
    FROM WEATHER_DB.RAW.WEATHER_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) AS source

ON target.CITY = source.CITY
AND target.WEATHER_TIME = source.WEATHER_TIME

WHEN MATCHED THEN
    UPDATE SET
        target.TEMPERATURE = source.TEMPERATURE,
        target.HUMIDITY = source.HUMIDITY,
        target.PRESSURE = source.PRESSURE,
        target.WIND_SPEED = source.WIND_SPEED,
        target.WEATHER_CODE = source.WEATHER_CODE,
        target.PRECIPITATION = source.PRECIPITATION

WHEN NOT MATCHED THEN
    INSERT (
        CITY,
        WEATHER_TIME,
        TEMPERATURE,
        HUMIDITY,
        PRESSURE,
        WIND_SPEED,
        WEATHER_CODE,
        PRECIPITATION
    )
    VALUES (
        source.CITY,
        source.WEATHER_TIME,
        source.TEMPERATURE,
        source.HUMIDITY,
        source.PRESSURE,
        source.WIND_SPEED,
        source.WEATHER_CODE,
        source.PRECIPITATION
    );
