USE DATABASE WEATHER_DB;
USE SCHEMA ANALYTICS;

CREATE DYNAMIC TABLE IF NOT EXISTS WEATHER_ANALYTICS_DT
TARGET_LAG = '1 hour'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    CITY,
    WEATHER_TIME,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WIND_SPEED,
    WEATHER_CODE,
    PRECIPITATION,

    CAST(WEATHER_TIME AS DATE) AS WEATHER_DATE,

    CASE
        WHEN TEMPERATURE < 20 THEN 'COOL'
        WHEN TEMPERATURE BETWEEN 20 AND 30 THEN 'MODERATE'
        ELSE 'HOT'
    END AS TEMP_CATEGORY,

    CASE
        WHEN WIND_SPEED < 10 THEN 'LOW'
        WHEN WIND_SPEED BETWEEN 10 AND 25 THEN 'MODERATE'
        ELSE 'HIGH'
    END AS WIND_CATEGORY

FROM WEATHER_DB.STAGING.WEATHER_STAGING;