USE DATABASE WEATHER_DB;
USE SCHEMA ANALYTICS;


-- City-level weather summary

CREATE OR REPLACE VIEW CITY_WEATHER_SUMMARY AS
SELECT
    CITY,
    COUNT(*) AS TOTAL_OBSERVATIONS,
    ROUND(AVG(TEMPERATURE), 2) AS AVG_TEMPERATURE,
    ROUND(MIN(TEMPERATURE), 2) AS MIN_TEMPERATURE,
    ROUND(MAX(TEMPERATURE), 2) AS MAX_TEMPERATURE,
    ROUND(AVG(HUMIDITY), 2) AS AVG_HUMIDITY,
    ROUND(MAX(WIND_SPEED), 2) AS MAX_WIND_SPEED,
    ROUND(SUM(PRECIPITATION), 2) AS TOTAL_PRECIPITATION
FROM WEATHER_ANALYTICS_DT
GROUP BY CITY;


-- Daily weather summary

CREATE OR REPLACE VIEW DAILY_WEATHER_SUMMARY AS
SELECT
    CITY,
    WEATHER_DATE,
    COUNT(*) AS OBSERVATIONS,
    ROUND(AVG(TEMPERATURE), 2) AS AVG_TEMPERATURE,
    ROUND(MIN(TEMPERATURE), 2) AS MIN_TEMPERATURE,
    ROUND(MAX(TEMPERATURE), 2) AS MAX_TEMPERATURE,
    ROUND(AVG(HUMIDITY), 2) AS AVG_HUMIDITY,
    ROUND(MAX(WIND_SPEED), 2) AS MAX_WIND_SPEED,
    ROUND(SUM(PRECIPITATION), 2) AS TOTAL_PRECIPITATION
FROM WEATHER_ANALYTICS_DT
GROUP BY CITY, WEATHER_DATE;


-- Latest weather for each city

CREATE OR REPLACE VIEW LATEST_WEATHER AS
SELECT
    CITY,
    WEATHER_TIME,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WIND_SPEED,
    PRECIPITATION,
    WEATHER_CODE,
    TEMP_CATEGORY,
    WIND_CATEGORY
FROM WEATHER_ANALYTICS_DT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CITY
    ORDER BY WEATHER_TIME DESC
) = 1;